import { motion } from "framer-motion";
import { Globe, MessageCircle, Smartphone, Phone } from "lucide-react";
import { CodeBlock } from "@/components/gitAgent/CodeBlock";

const composioCode = `# Set up Composio
export COMPOSIO_API_KEY=your-key
gitagent --voice --dir ~/assistant

# Then in the Integrations tab, connect Gmail, Slack, GitHub, etc.
# The agent will have access to those services as tools automatically`;

const twilioWebhookCode = `Webhook URL: https://your-server:3333/api/phone/webhook`;

export function GitAgentIntegrations() {
  return (
    <section id="integrations" className="py-16 px-0 border-t border-border">
      <div className="mx-auto max-w-6xl px-6">
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-8"
        >
          <h2 className="text-2xl font-bold text-foreground mb-2 font-heading">Integrations</h2>
          <p className="text-sm text-muted-foreground font-body">
            Connect GitAgent to external services via Composio, Telegram, WhatsApp, and Twilio.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-8">
          {/* A. Composio card */}
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="paper-card p-4 hover:border-primary/40 transition-colors border-primary/20"
          >
            <div className="flex items-center gap-2 mb-3 relative z-10">
              <Globe className="w-4 h-4 text-primary shrink-0" />
              <span className="text-sm font-semibold text-foreground font-heading">Composio</span>
              <span className="ml-auto text-[10px] px-2 py-0.5 rounded bg-primary/10 text-primary font-body">
                200+ integrations
              </span>
            </div>
            <div className="space-y-2 relative z-10">
              <div className="flex items-center gap-2">
                <span className="text-[10px] text-muted-foreground/60 font-body uppercase tracking-wider shrink-0">Requires</span>
                <code className="text-[10px] text-primary font-body">COMPOSIO_API_KEY</code>
              </div>
              <p className="text-[11px] text-muted-foreground font-body leading-relaxed">
                Enables 200+ integrations: Gmail, Calendar, Slack, GitHub, Notion, Linear, Salesforce, and more.
              </p>
              <p className="text-[11px] text-muted-foreground font-body leading-relaxed">
                Configure in the Integrations tab of the web UI.
              </p>
              <p className="text-[11px] text-muted-foreground font-body leading-relaxed">
                GitAgent tools map directly to Composio actions.
              </p>
            </div>
          </motion.div>

          {/* B. Telegram card */}
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.04 }}
            className="paper-card p-4 hover:border-primary/40 transition-colors"
          >
            <div className="flex items-center gap-2 mb-3 relative z-10">
              <MessageCircle className="w-4 h-4 text-primary shrink-0" />
              <span className="text-sm font-semibold text-foreground font-heading">Telegram</span>
            </div>
            <div className="space-y-2 relative z-10">
              <div className="flex items-center gap-2">
                <span className="text-[10px] text-muted-foreground/60 font-body uppercase tracking-wider shrink-0">Requires</span>
                <code className="text-[10px] text-primary font-body">TELEGRAM_BOT_TOKEN</code>
              </div>
              <div className="space-y-1.5">
                {[
                  "Create bot via @BotFather → Enter token in Communication tab",
                  "Configure allowed users for access control",
                  "Files generated by the agent are auto-sent to Telegram",
                  "Used for approval gates in SkillFlows",
                ].map((item, i) => (
                  <div key={i} className="flex items-start gap-2">
                    <span className="text-primary text-xs mt-0.5 shrink-0">—</span>
                    <p className="text-[11px] text-muted-foreground font-body leading-relaxed">{item}</p>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>

          {/* C. WhatsApp card */}
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.08 }}
            className="paper-card p-4 hover:border-primary/40 transition-colors"
          >
            <div className="flex items-center gap-2 mb-3 relative z-10">
              <Smartphone className="w-4 h-4 text-primary shrink-0" />
              <span className="text-sm font-semibold text-foreground font-heading">WhatsApp</span>
            </div>
            <div className="space-y-1.5 relative z-10">
              {[
                "Uses Baileys library — no phone number API needed",
                "Connect via QR code in Communication tab",
                "Session persists across restarts",
                "Auto-responds to messages from your number",
              ].map((item, i) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="text-primary text-xs mt-0.5 shrink-0">—</span>
                  <p className="text-[11px] text-muted-foreground font-body leading-relaxed">{item}</p>
                </div>
              ))}
            </div>
          </motion.div>

          {/* D. Phone / SMS (Twilio) card */}
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.12 }}
            className="paper-card p-4 hover:border-primary/40 transition-colors"
          >
            <div className="flex items-center gap-2 mb-3 relative z-10">
              <Phone className="w-4 h-4 text-primary shrink-0" />
              <span className="text-sm font-semibold text-foreground font-heading">Phone / SMS (Twilio)</span>
            </div>
            <div className="space-y-3 relative z-10">
              <p className="text-[11px] text-muted-foreground font-body leading-relaxed">
                Configure this webhook URL in your Twilio console:
              </p>
              <CodeBlock code={twilioWebhookCode} filename="Twilio Webhook" />
            </div>
          </motion.div>
        </div>

        {/* E. Composio example */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h3 className="text-xs uppercase tracking-widest text-muted-foreground/60 mb-4 font-body">
            Composio Quick Start
          </h3>
          <CodeBlock code={composioCode} filename="terminal" />
        </motion.div>
      </div>
    </section>
  );
}
